---
title: "Lecture 5 -- Demos for the testing lecture"
author: "Wolfgang Huber"
output:
  BiocStyle::html_document2:
    toc: true
    toc_depth: 2
vignette: >
  % \VignetteEngine{knitr::rmarkdown}
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(tidy = FALSE, cache = TRUE, autodep = TRUE,
            message = FALSE, error = FALSE, warning = TRUE)
```

# p-values

```{r pvalues-setup}
library("genefilter")
library("ggplot2")
library("dplyr")
library("gridExtra")

n = 20
m = 10000
x = matrix(rnorm(n*m), ncol = n, nrow = m)
fac = factor((seq_len(n)-1) %/% (n/2))
rt = rowttests(x, fac)
rt = mutate(rt, `|t|` = abs(statistic))

alpha = 0.05

gh = geom_histogram(fill = "skyblue", bins = 50, boundary = 0)

pvalues_plot = function(stage) {
  g1 = ggplot(rt, aes(x = `|t|`)) + gh 
  g2 = ggplot(rt, aes(x = `|t|`)) + stat_ecdf() + ylab("1 - p") 
  g3 = ggplot(rt, aes(x = p.value))  + gh 

  if (stage >= 2) { 
    g2 = g2 + geom_hline(
      aes(yintercept = 1-alpha), col = "orange")  
    g3 = g3 + geom_vline(
      aes(xintercept = quantile(rt$p.value, probs = alpha)), col = "orange")
  }
  if (stage >= 3) {
    g1 = g1 + geom_vline(
      aes(xintercept = quantile(`|t|`, probs = 1 - alpha)), col = "red")
    g2 = g2 + geom_vline(
      aes(xintercept = quantile(`|t|`, probs = 1 - alpha)), col = "red")
   }
   grid.arrange(g1, g2, g3, ncol = 3)
}
```
 
NB: Having a single code chunk with ``dev=c("png", "pdf")`` somehow messed up the formatting when I tried, hence I am doing it with two.

```{r pvalues-png, dev = "png", fig.width = 8, fig.height = 2.5}
for (i in 1:3) pvalues_plot(i) 
```{r pvalues-pdf, dev = "pdf", fig.width = 8, fig.height = 2.5, include = FALSE}
for (i in 1:3) pvalues_plot(i) 
```

